### PR TITLE
add some missing governance docs

### PR DESCRIPTION
**Pull request by duglin**

### CODE REVIEW

**Comment by duglin** [comment]
ping @markpeek @embano1

**Comment by embano1** [comment]
Thx @duglin. I'm in favor of archiving this repo since it's been unmaintained for some time. Unless @markpeek and @lamw object (we need active maintainership to keep the repo up2date with security patches and releases).

**Comment by duglin** [comment]
@dmilov any comments?

**Comment by duglin** [comment]
I'll bring this up on this week's call. Will probably ask about some other SDKs too.... thanks for the idea

**Review by markpeek — APPROVED** [review]

**Comment by markpeek** [comment]
Approving and merging. And @lamw and @markpeek will keep an eye on changes in this repo to keep it active/current.

**Pull request merged**
